import userRouter from "./users.route";
import authRouter from "./auth.route";
import articleRouter from "./article.route";
import shopRouter from "./shop.route";
import storeRouter from "./store.route";
import utileRouter from "./utile.route";
import paymentRouter from "./payment.route";
import cartRouter from "./cart.route";
import orderRouter from "./order.route";
import categoriesRouter from "./category.route";
import usersRouter from "./users.route";
import ordersRouter from "./order.route";
import permissionsRouter from "./permission.route";
import rolesRouter from "./role.route";
import subcategoriesRouter from "./subcategory.route";
import dashboardRouter from "./dashboard.route";
export { dashboardRouter,subcategoriesRouter,rolesRouter,permissionsRouter,ordersRouter,orderRouter,cartRouter,userRouter, authRouter, articleRouter,shopRouter,storeRouter,utileRouter,paymentRouter,categoriesRouter,usersRouter};
